import { StyleSheet } from "react-native";

export function createNotesManagerStyles() {
  return {
    notesManagerPage: {
      backgroundColor: "#0f1115",
      flex: 1,
      paddingHorizontal: 14,
      paddingTop: 8,
    },
    notesManagerTopBar: {
      alignItems: "center",
      borderBottomColor: "rgba(255, 255, 255, 0.06)",
      borderBottomWidth: StyleSheet.hairlineWidth,
      flexDirection: "row",
      gap: 12,
      paddingBottom: 14,
      paddingTop: 8,
    },
    notesManagerBackBtn: {
      alignItems: "center",
      backgroundColor: "rgba(255, 255, 255, 0.08)",
      borderColor: "rgba(255, 255, 255, 0.08)",
      borderRadius: 8,
      borderWidth: StyleSheet.hairlineWidth,
      height: 36,
      justifyContent: "center",
      width: 36,
    },
    notesManagerBackIcon: {
      color: "#ffffff",
      fontSize: 28,
      fontWeight: "300",
      lineHeight: 31,
    },
    notesManagerHeading: {
      flex: 1,
      minWidth: 0,
    },
    notesManagerEyebrow: {
      color: "rgba(255, 255, 255, 0.45)",
      fontSize: 11,
      fontWeight: "800",
      letterSpacing: 0,
      textTransform: "uppercase",
    },
    notesManagerTitle: {
      color: "#ffffff",
      fontSize: 22,
      fontWeight: "800",
      marginTop: 2,
    },
    notesManagerNewBtn: {
      alignItems: "center",
      backgroundColor: "#3b82f6",
      borderRadius: 8,
      justifyContent: "center",
      paddingHorizontal: 12,
      paddingVertical: 9,
    },
    notesManagerNewText: {
      color: "#ffffff",
      fontSize: 13,
      fontWeight: "800",
    },
    notesManagerSummary: {
      alignItems: "center",
      backgroundColor: "#15181d",
      borderColor: "rgba(255, 255, 255, 0.08)",
      borderRadius: 8,
      borderWidth: StyleSheet.hairlineWidth,
      flexDirection: "row",
      marginTop: 14,
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
    notesManagerSummaryItem: {
      flex: 1,
    },
    notesManagerSummaryValue: {
      color: "#ffffff",
      fontSize: 22,
      fontWeight: "800",
    },
    notesManagerSummaryLabel: {
      color: "rgba(255, 255, 255, 0.52)",
      fontSize: 12,
      fontWeight: "700",
      marginTop: 2,
    },
    notesManagerSummaryDivider: {
      backgroundColor: "rgba(255, 255, 255, 0.08)",
      height: 34,
      width: StyleSheet.hairlineWidth,
    },
    notesManagerScroll: {
      flex: 1,
      marginTop: 14,
    },
    notesManagerList: {
      gap: 10,
      paddingBottom: 24,
    },
    notesManagerItem: {
      backgroundColor: "rgba(255, 255, 255, 0.06)",
      borderColor: "rgba(255, 255, 255, 0.08)",
      borderRadius: 8,
      borderWidth: 1,
      padding: 12,
    },
    notesManagerItemActive: {
      backgroundColor: "#18284a",
      borderColor: "#3b82f6",
    },
    notesManagerItemMain: {
      alignItems: "center",
      flexDirection: "row",
      gap: 12,
      minHeight: 50,
    },
    notesManagerItemIcon: {
      alignItems: "center",
      backgroundColor: "rgba(59, 130, 246, 0.16)",
      borderColor: "rgba(59, 130, 246, 0.35)",
      borderRadius: 8,
      borderWidth: StyleSheet.hairlineWidth,
      height: 42,
      justifyContent: "center",
      width: 42,
    },
    notesManagerItemIconText: {
      color: "#bfdbfe",
      fontSize: 14,
      fontWeight: "800",
    },
    notesManagerItemCopy: {
      flex: 1,
      minWidth: 0,
    },
    notesManagerItemTitle: {
      color: "#ffffff",
      fontSize: 16,
      fontWeight: "700",
    },
    notesManagerItemMeta: {
      color: "rgba(255, 255, 255, 0.5)",
      fontSize: 12,
      fontWeight: "600",
      marginTop: 3,
    },
    notesManagerActivePill: {
      backgroundColor: "rgba(59, 130, 246, 0.2)",
      borderColor: "rgba(147, 197, 253, 0.3)",
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      color: "#bfdbfe",
      fontSize: 11,
      fontWeight: "800",
      overflow: "hidden",
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    notesManagerDeleteBtn: {
      alignItems: "center",
      borderColor: "rgba(248, 113, 113, 0.42)",
      borderRadius: 8,
      borderWidth: 1,
      marginTop: 10,
      paddingVertical: 9,
    },
    notesManagerDeleteText: {
      color: "#fca5a5",
      fontSize: 12,
      fontWeight: "800",
    },
  } as const;
}
