import { StyleSheet } from "react-native";

export function createNotesToolbarStyles() {
  return {
    notesBottomBar: {
      backgroundColor: "#18191c",
      borderTopColor: "rgba(255, 255, 255, 0.1)",
      borderTopWidth: StyleSheet.hairlineWidth,
      gap: 8,
      paddingBottom: 10,
      paddingHorizontal: 10,
      paddingTop: 10,
    },
    notesUtensilToggle: {
      alignItems: "center",
      backgroundColor: "#25272c",
      borderColor: "rgba(255, 255, 255, 0.1)",
      borderRadius: 28,
      borderWidth: 1,
      bottom: 18,
      height: 56,
      justifyContent: "center",
      left: 18,
      position: "absolute",
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.35,
      shadowRadius: 10,
      width: 56,
      elevation: 8,
      zIndex: 4,
    },
    notesUtensilToggleOpen: {
      bottom: 108,
    },
    notesUtensilToggleIcon: {
      color: "#ffffff",
      fontSize: 30,
      fontWeight: "600",
      lineHeight: 32,
    },
    notesToolRow: {
      alignItems: "flex-end",
      flexDirection: "row",
      gap: 4,
      justifyContent: "center",
      paddingHorizontal: 4,
    },
    notesToolBtn: {
      alignItems: "center",
      borderColor: "transparent",
      borderRadius: 12,
      borderWidth: 1.5,
      gap: 3,
      justifyContent: "flex-end",
      paddingBottom: 4,
      paddingTop: 6,
      width: 54,
    },
    notesToolBtnActive: {
      backgroundColor: "rgba(255, 255, 255, 0.08)",
      borderColor: "rgba(255, 255, 255, 0.22)",
    },
    utensilLabel: {
      color: "rgba(255, 255, 255, 0.4)",
      fontSize: 9,
      fontWeight: "700",
      letterSpacing: 0.3,
    },
    utensilLabelActive: {
      color: "rgba(255, 255, 255, 0.85)",
    },
    utensilWrap: {
      alignItems: "center",
      height: 44,
      justifyContent: "flex-end",
      width: 36,
    },
    penTip: {
      borderBottomWidth: 10,
      borderLeftColor: "transparent",
      borderLeftWidth: 4,
      borderRightColor: "transparent",
      borderRightWidth: 4,
      height: 0,
      width: 0,
    },
    penBarrel: {
      backgroundColor: "#2a2d32",
      borderRadius: 2,
      borderWidth: 1.5,
      height: 28,
      width: 10,
    },
    penGrip: {
      backgroundColor: "#44474d",
      borderBottomLeftRadius: 2,
      borderBottomRightRadius: 2,
      height: 6,
      marginTop: -1,
      width: 12,
    },
    markerNib: {
      borderRadius: 1,
      height: 6,
      width: 8,
    },
    markerBarrel: {
      backgroundColor: "#2a2d32",
      borderRadius: 3,
      borderWidth: 1.5,
      height: 32,
      width: 14,
    },
    highlighterTip: {
      borderRadius: 2,
      height: 8,
      width: 16,
    },
    highlighterBarrel: {
      backgroundColor: "#2a2d32",
      borderRadius: 4,
      borderWidth: 1.5,
      height: 30,
      width: 18,
    },
    eraserTop: {
      backgroundColor: "#f28c8c",
      borderTopLeftRadius: 4,
      borderTopRightRadius: 4,
      height: 10,
      width: 18,
    },
    eraserBody: {
      backgroundColor: "#3a3d42",
      borderBottomLeftRadius: 2,
      borderBottomRightRadius: 2,
      height: 26,
      width: 18,
    },
    textToolBox: {
      alignItems: "center",
      borderRadius: 6,
      borderWidth: 1.5,
      height: 32,
      justifyContent: "center",
      width: 28,
    },
    textToolLetter: {
      fontSize: 16,
      fontWeight: "800",
    },
    notesColorBtn: {
      alignItems: "center",
      backgroundColor: "rgba(255, 255, 255, 0.06)",
      borderColor: "rgba(255, 255, 255, 0.15)",
      borderRadius: 12,
      borderWidth: 1.5,
      height: 40,
      justifyContent: "center",
      marginBottom: 4,
      marginLeft: 2,
      width: 40,
    },
    notesColorBtnDot: {
      borderColor: "rgba(255,255,255,0.3)",
      borderRadius: 999,
      borderWidth: 1,
      height: 22,
      width: 22,
    },
    colorPickerOverlay: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: "flex-end",
    },
    colorPickerScrim: {
      ...StyleSheet.absoluteFillObject,
    },
    colorPickerPanel: {
      alignItems: "center",
      alignSelf: "center",
      backgroundColor: "#1e2028",
      borderColor: "rgba(255, 255, 255, 0.14)",
      borderRadius: 20,
      borderWidth: 1,
      bottom: 110,
      flexDirection: "row",
      gap: 10,
      paddingHorizontal: 14,
      paddingVertical: 10,
      position: "absolute",
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 12,
      elevation: 8,
    },
    colorPickerDot: {
      borderColor: "rgba(255, 255, 255, 0.12)",
      borderRadius: 999,
      borderWidth: 2,
      height: 30,
      width: 30,
    },
    colorPickerDotActive: {
      borderColor: "#ffffff",
      borderWidth: 2.5,
      transform: [{ scale: 1.15 }],
    },
  } as const;
}
