import { StyleSheet } from "react-native";

export function createNotesNavigationStyles() {
  return {
    notesHeader: {
      alignItems: "center",
      borderBottomColor: "rgba(255, 255, 255, 0.06)",
      borderBottomWidth: 1,
      flexDirection: "row",
      gap: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    notesBackBtn: {
      alignItems: "center",
      backgroundColor: "rgba(255, 255, 255, 0.08)",
      borderRadius: 8,
      height: 30,
      justifyContent: "center",
      width: 30,
    },
    notesBackIcon: {
      color: "#ffffff",
      fontSize: 24,
      fontWeight: "300",
      lineHeight: 28,
    },
    notesHeaderCenter: {
      flex: 1,
    },
    notesTitle: {
      color: "#ffffff",
      fontSize: 17,
      fontWeight: "600",
    },
    notesPageBadge: {
      color: "rgba(255, 255, 255, 0.4)",
      fontSize: 13,
      fontWeight: "600",
    },
    notesSaveBtn: {
      alignItems: "center",
      backgroundColor: "#3b82f6",
      borderRadius: 8,
      height: 30,
      justifyContent: "center",
      width: 30,
    },
    notesSaveIcon: {
      color: "#ffffff",
      fontSize: 16,
      fontWeight: "700",
    },
    notesManagerBtn: {
      alignItems: "center",
      backgroundColor: "rgba(255, 255, 255, 0.08)",
      borderRadius: 8,
      height: 30,
      justifyContent: "center",
      width: 30,
    },
    notesManagerIcon: {
      color: "#ffffff",
      fontSize: 17,
      fontWeight: "800",
    },
    notesPageControlsBar: {
      alignItems: "center",
      backgroundColor: "#15181d",
      borderBottomColor: "rgba(255, 255, 255, 0.06)",
      borderBottomWidth: StyleSheet.hairlineWidth,
      flexDirection: "row",
      gap: 7,
      paddingHorizontal: 10,
      paddingVertical: 7,
    },
    notesPageIconBtn: {
      alignItems: "center",
      backgroundColor: "rgba(255, 255, 255, 0.07)",
      borderColor: "rgba(255, 255, 255, 0.1)",
      borderRadius: 8,
      borderWidth: StyleSheet.hairlineWidth,
      height: 30,
      justifyContent: "center",
      width: 30,
    },
    notesPageIconText: {
      color: "rgba(255, 255, 255, 0.82)",
      fontSize: 18,
      fontWeight: "700",
      lineHeight: 20,
    },
    notesPageStatus: {
      flex: 1,
      minWidth: 0,
    },
    notesPageStatusText: {
      color: "rgba(255, 255, 255, 0.58)",
      fontSize: 12,
      fontWeight: "700",
    },
    notesPageActionBtn: {
      alignItems: "center",
      backgroundColor: "#2563eb",
      borderRadius: 8,
      height: 30,
      justifyContent: "center",
      paddingHorizontal: 10,
    },
    notesPageActionText: {
      color: "#ffffff",
      fontSize: 12,
      fontWeight: "800",
    },
    notesPageDeleteBtn: {
      alignItems: "center",
      backgroundColor: "rgba(248, 113, 113, 0.12)",
      borderColor: "rgba(248, 113, 113, 0.34)",
      borderRadius: 8,
      borderWidth: StyleSheet.hairlineWidth,
      height: 30,
      justifyContent: "center",
      paddingHorizontal: 9,
    },
    notesPageDeleteText: {
      color: "#fca5a5",
      fontSize: 12,
      fontWeight: "800",
    },
    notesPageRow: {
      alignItems: "center",
      flexDirection: "row",
      gap: 10,
      justifyContent: "center",
    },
    notesPageBtn: {
      alignItems: "center",
      backgroundColor: "rgba(255, 255, 255, 0.06)",
      borderColor: "rgba(255, 255, 255, 0.1)",
      borderRadius: 8,
      borderWidth: StyleSheet.hairlineWidth,
      height: 30,
      justifyContent: "center",
      width: 30,
    },
    notesPageBtnDisabled: {
      opacity: 0.2,
    },
    notesPageBtnText: {
      color: "rgba(255, 255, 255, 0.8)",
      fontSize: 16,
      fontWeight: "600",
      lineHeight: 18,
    },
    notesNewPageBtn: {
      alignItems: "center",
      backgroundColor: "rgba(255, 255, 255, 0.06)",
      borderColor: "rgba(255, 255, 255, 0.1)",
      borderRadius: 8,
      borderWidth: StyleSheet.hairlineWidth,
      justifyContent: "center",
      paddingHorizontal: 14,
      paddingVertical: 7,
    },
    notesNewPageBtnDisabled: {
      opacity: 0.3,
    },
    notesNewPageText: {
      color: "rgba(255, 255, 255, 0.6)",
      fontSize: 12,
      fontWeight: "600",
    },
  } as const;
}
