import { StyleSheet } from 'react-native';

import type { CalculatorTheme } from '../../theme';

export function createNotesStyles(_theme: CalculatorTheme) {
  return StyleSheet.create({
    notesContainer: {
      backgroundColor: '#0f1115',
      flex: 1,
      overflow: 'hidden',
    },
    notesHeader: {
      alignItems: 'center',
      borderBottomColor: 'rgba(255, 255, 255, 0.06)',
      borderBottomWidth: 1,
      flexDirection: 'row',
      gap: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    notesBackBtn: {
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.08)',
      borderRadius: 8,
      height: 30,
      justifyContent: 'center',
      width: 30,
    },
    notesBackIcon: {
      color: '#ffffff',
      fontSize: 24,
      fontWeight: '300',
      lineHeight: 28,
    },
    notesHeaderCenter: {
      flex: 1,
    },
    notesTitle: {
      color: '#ffffff',
      fontSize: 17,
      fontWeight: '600',
    },
    notesPageBadge: {
      color: 'rgba(255, 255, 255, 0.4)',
      fontSize: 13,
      fontWeight: '600',
    },
    notesSaveBtn: {
      alignItems: 'center',
      backgroundColor: '#3b82f6',
      borderRadius: 8,
      height: 30,
      justifyContent: 'center',
      width: 30,
    },
    notesSaveIcon: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: '700',
    },
    notesManagerBtn: {
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.08)',
      borderRadius: 8,
      height: 30,
      justifyContent: 'center',
      width: 30,
    },
    notesManagerIcon: {
      color: '#ffffff',
      fontSize: 17,
      fontWeight: '800',
    },
    notesPageControlsBar: {
      alignItems: 'center',
      backgroundColor: '#15181d',
      borderBottomColor: 'rgba(255, 255, 255, 0.06)',
      borderBottomWidth: StyleSheet.hairlineWidth,
      flexDirection: 'row',
      gap: 7,
      paddingHorizontal: 10,
      paddingVertical: 7,
    },
    notesPageIconBtn: {
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.07)',
      borderColor: 'rgba(255, 255, 255, 0.1)',
      borderRadius: 8,
      borderWidth: StyleSheet.hairlineWidth,
      height: 30,
      justifyContent: 'center',
      width: 30,
    },
    notesPageIconText: {
      color: 'rgba(255, 255, 255, 0.82)',
      fontSize: 18,
      fontWeight: '700',
      lineHeight: 20,
    },
    notesPageStatus: {
      flex: 1,
      minWidth: 0,
    },
    notesPageStatusText: {
      color: 'rgba(255, 255, 255, 0.58)',
      fontSize: 12,
      fontWeight: '700',
    },
    notesPageActionBtn: {
      alignItems: 'center',
      backgroundColor: '#2563eb',
      borderRadius: 8,
      height: 30,
      justifyContent: 'center',
      paddingHorizontal: 10,
    },
    notesPageActionText: {
      color: '#ffffff',
      fontSize: 12,
      fontWeight: '800',
    },
    notesPageDeleteBtn: {
      alignItems: 'center',
      backgroundColor: 'rgba(248, 113, 113, 0.12)',
      borderColor: 'rgba(248, 113, 113, 0.34)',
      borderRadius: 8,
      borderWidth: StyleSheet.hairlineWidth,
      height: 30,
      justifyContent: 'center',
      paddingHorizontal: 9,
    },
    notesPageDeleteText: {
      color: '#fca5a5',
      fontSize: 12,
      fontWeight: '800',
    },
    notesCanvasWrap: {
      borderColor: 'rgba(255, 255, 255, 0.06)',
      borderRadius: 12,
      borderWidth: 1,
      flex: 1,
      marginHorizontal: 10,
      marginTop: 6,
      overflow: 'hidden',
    },
    notesCanvas: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: '#121418',
    },
    notesDot: {
      backgroundColor: 'rgba(255, 255, 255, 0.07)',
      borderRadius: 999,
      height: 1.5,
      position: 'absolute',
      width: 1.5,
    },
    strokeSegment: {
      borderRadius: 999,
      position: 'absolute',
      transformOrigin: 'left center',
    },
    canvasTextBlockWrap: {
      alignItems: 'flex-start',
      flexDirection: 'row',
      position: 'absolute',
    },
    canvasTextBlock: {
      backgroundColor: 'rgba(15, 17, 21, 0.72)',
      borderColor: 'rgba(255, 255, 255, 0.1)',
      borderRadius: 8,
      borderWidth: StyleSheet.hairlineWidth,
      fontSize: 22,
      fontWeight: '600',
      maxWidth: 280,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    textBlockDelete: {
      alignItems: 'center',
      backgroundColor: '#ef4444',
      borderRadius: 999,
      height: 20,
      justifyContent: 'center',
      marginLeft: -10,
      marginTop: -6,
      width: 20,
    },
    textBlockDeleteIcon: {
      color: '#ffffff',
      fontSize: 10,
      fontWeight: '700',
    },
    notesTextBar: {
      alignItems: 'center',
      backgroundColor: '#1a1d22',
      borderColor: 'rgba(255, 255, 255, 0.08)',
      borderRadius: 10,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 6,
      marginHorizontal: 10,
      marginTop: 6,
      padding: 5,
    },
    notesTextInput: {
      color: '#ffffff',
      flex: 1,
      fontSize: 14,
      minHeight: 32,
      paddingHorizontal: 10,
    },
    notesTextAddBtn: {
      alignItems: 'center',
      backgroundColor: '#3b82f6',
      borderRadius: 6,
      justifyContent: 'center',
      minHeight: 32,
      paddingHorizontal: 14,
    },
    notesTextAddLabel: {
      color: '#ffffff',
      fontSize: 14,
      fontWeight: '700',
    },
    notesBottomBar: {
      backgroundColor: '#18191c',
      borderTopColor: 'rgba(255, 255, 255, 0.1)',
      borderTopWidth: StyleSheet.hairlineWidth,
      gap: 8,
      paddingBottom: 10,
      paddingHorizontal: 10,
      paddingTop: 10,
    },
    notesToolRow: {
      alignItems: 'flex-end',
      flexDirection: 'row',
      gap: 4,
      justifyContent: 'center',
      paddingHorizontal: 4,
    },
    notesToolBtn: {
      alignItems: 'center',
      borderColor: 'transparent',
      borderRadius: 12,
      borderWidth: 1.5,
      gap: 3,
      justifyContent: 'flex-end',
      paddingBottom: 4,
      paddingTop: 6,
      width: 54,
    },
    notesToolBtnActive: {
      backgroundColor: 'rgba(255, 255, 255, 0.08)',
      borderColor: 'rgba(255, 255, 255, 0.22)',
    },
    utensilLabel: {
      color: 'rgba(255, 255, 255, 0.4)',
      fontSize: 9,
      fontWeight: '700',
      letterSpacing: 0.3,
    },
    utensilLabelActive: {
      color: 'rgba(255, 255, 255, 0.85)',
    },
    utensilWrap: {
      alignItems: 'center',
      height: 44,
      justifyContent: 'flex-end',
      width: 36,
    },
    penTip: {
      borderBottomWidth: 10,
      borderLeftColor: 'transparent',
      borderLeftWidth: 4,
      borderRightColor: 'transparent',
      borderRightWidth: 4,
      height: 0,
      width: 0,
    },
    penBarrel: {
      backgroundColor: '#2a2d32',
      borderRadius: 2,
      borderWidth: 1.5,
      height: 28,
      width: 10,
    },
    penGrip: {
      backgroundColor: '#44474d',
      borderBottomLeftRadius: 2,
      borderBottomRightRadius: 2,
      height: 6,
      marginTop: -1,
      width: 12,
    },
    markerNib: {
      borderRadius: 1,
      height: 6,
      width: 8,
    },
    markerBarrel: {
      backgroundColor: '#2a2d32',
      borderRadius: 3,
      borderWidth: 1.5,
      height: 32,
      width: 14,
    },
    highlighterTip: {
      borderRadius: 2,
      height: 8,
      width: 16,
    },
    highlighterBarrel: {
      backgroundColor: '#2a2d32',
      borderRadius: 4,
      borderWidth: 1.5,
      height: 30,
      width: 18,
    },
    eraserTop: {
      backgroundColor: '#f28c8c',
      borderTopLeftRadius: 4,
      borderTopRightRadius: 4,
      height: 10,
      width: 18,
    },
    eraserBody: {
      backgroundColor: '#3a3d42',
      borderBottomLeftRadius: 2,
      borderBottomRightRadius: 2,
      height: 26,
      width: 18,
    },
    textToolBox: {
      alignItems: 'center',
      borderRadius: 6,
      borderWidth: 1.5,
      height: 32,
      justifyContent: 'center',
      width: 28,
    },
    textToolLetter: {
      fontSize: 16,
      fontWeight: '800',
    },
    notesColorBtn: {
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.06)',
      borderColor: 'rgba(255, 255, 255, 0.15)',
      borderRadius: 12,
      borderWidth: 1.5,
      height: 40,
      justifyContent: 'center',
      marginBottom: 4,
      marginLeft: 2,
      width: 40,
    },
    notesColorBtnDot: {
      borderColor: 'rgba(255,255,255,0.3)',
      borderRadius: 999,
      borderWidth: 1,
      height: 22,
      width: 22,
    },
    colorPickerOverlay: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: 'flex-end',
    },
    colorPickerScrim: {
      ...StyleSheet.absoluteFillObject,
    },
    colorPickerPanel: {
      alignItems: 'center',
      alignSelf: 'center',
      backgroundColor: '#1e2028',
      borderColor: 'rgba(255, 255, 255, 0.14)',
      borderRadius: 20,
      borderWidth: 1,
      bottom: 110,
      flexDirection: 'row',
      gap: 10,
      paddingHorizontal: 14,
      paddingVertical: 10,
      position: 'absolute',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 12,
      elevation: 8,
    },
    colorPickerDot: {
      borderColor: 'rgba(255, 255, 255, 0.12)',
      borderRadius: 999,
      borderWidth: 2,
      height: 30,
      width: 30,
    },
    colorPickerDotActive: {
      borderColor: '#ffffff',
      borderWidth: 2.5,
      transform: [{ scale: 1.15 }],
    },
    notesPageRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 10,
      justifyContent: 'center',
    },
    notesPageBtn: {
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.06)',
      borderColor: 'rgba(255, 255, 255, 0.1)',
      borderRadius: 8,
      borderWidth: StyleSheet.hairlineWidth,
      height: 30,
      justifyContent: 'center',
      width: 30,
    },
    notesPageBtnDisabled: {
      opacity: 0.2,
    },
    notesPageBtnText: {
      color: 'rgba(255, 255, 255, 0.8)',
      fontSize: 16,
      fontWeight: '600',
      lineHeight: 18,
    },
    notesNewPageBtn: {
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.06)',
      borderColor: 'rgba(255, 255, 255, 0.1)',
      borderRadius: 8,
      borderWidth: StyleSheet.hairlineWidth,
      justifyContent: 'center',
      paddingHorizontal: 14,
      paddingVertical: 7,
    },
    notesNewPageBtnDisabled: {
      opacity: 0.3,
    },
    notesNewPageText: {
      color: 'rgba(255, 255, 255, 0.6)',
      fontSize: 12,
      fontWeight: '600',
    },
    notesManagerOverlay: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: 'flex-end',
    },
    notesManagerScrim: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0, 0, 0, 0.56)',
    },
    notesManagerSheet: {
      backgroundColor: '#15181d',
      borderTopColor: 'rgba(255, 255, 255, 0.08)',
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
      borderTopWidth: 1,
      maxHeight: '58%',
      paddingHorizontal: 14,
      paddingTop: 14,
    },
    notesManagerHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
    notesManagerTitle: {
      color: '#ffffff',
      fontSize: 18,
      fontWeight: '800',
    },
    notesManagerNewBtn: {
      alignItems: 'center',
      backgroundColor: '#3b82f6',
      borderRadius: 8,
      justifyContent: 'center',
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    notesManagerNewText: {
      color: '#ffffff',
      fontSize: 13,
      fontWeight: '800',
    },
    notesManagerList: {
      gap: 8,
      paddingBottom: 18,
    },
    notesManagerItem: {
      alignItems: 'center',
      backgroundColor: 'rgba(255, 255, 255, 0.06)',
      borderColor: 'rgba(255, 255, 255, 0.08)',
      borderRadius: 10,
      borderWidth: 1,
      flexDirection: 'row',
      padding: 10,
    },
    notesManagerItemActive: {
      backgroundColor: '#22324f',
      borderColor: '#3b82f6',
    },
    notesManagerItemMain: {
      flex: 1,
      paddingRight: 10,
    },
    notesManagerItemTitle: {
      color: '#ffffff',
      fontSize: 15,
      fontWeight: '700',
    },
    notesManagerItemMeta: {
      color: 'rgba(255, 255, 255, 0.5)',
      fontSize: 12,
      fontWeight: '600',
      marginTop: 3,
    },
    notesManagerDeleteBtn: {
      borderColor: 'rgba(248, 113, 113, 0.42)',
      borderRadius: 8,
      borderWidth: 1,
      paddingHorizontal: 10,
      paddingVertical: 7,
    },
    notesManagerDeleteText: {
      color: '#fca5a5',
      fontSize: 12,
      fontWeight: '800',
    },
  });
}
