import { StyleSheet } from "react-native";

import type { CalculatorTheme } from "@features/theme";

export function createCalculatorKeypadStyles(theme: CalculatorTheme) {
  return {
    sciFnSection: {
      gap: 0,
      marginHorizontal: 0,
    },
    sciFnRow: {
      flexDirection: "row",
      gap: 0,
    },
    sciFnButton: {
      alignItems: "center",
      backgroundColor: "transparent",
      borderBottomColor: theme.colors.divider,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderRightColor: theme.colors.divider,
      borderRightWidth: StyleSheet.hairlineWidth,
      flex: 1,
      justifyContent: "center",
      paddingHorizontal: 2,
      paddingVertical: 9,
    },
    sciFnButtonText: {
      color: theme.colors.sciFnText,
      fontSize: 15,
      fontWeight: "400",
    },
    sciFnButtonActive: {
      backgroundColor: theme.colors.buttonScientific,
    },
    sciFnButtonActiveText: {
      color: theme.colors.buttonText,
    },
    keypad: {
      gap: 12,
      paddingBottom: 12,
      paddingHorizontal: 16,
      paddingTop: 16,
    },
    scientificKeypad: {
      gap: 4,
      paddingBottom: 12,
      paddingHorizontal: 8,
      paddingTop: 4,
    },
    row: {
      alignItems: "center",
      flexDirection: "row",
      gap: 12,
      justifyContent: "space-between",
    },
    sciRow: {
      gap: 5,
    },
    button: {
      alignItems: "center",
      aspectRatio: 1,
      backgroundColor: theme.colors.buttonNumber,
      borderRadius: 999,
      flex: 1,
      justifyContent: "center",
    },
    sciNumButton: {
      aspectRatio: undefined,
      borderRadius: 10,
      paddingVertical: 10,
    },
    buttonWide: {
      aspectRatio: undefined,
      flex: 2,
    },
    buttonSpacer: {
      backgroundColor: "transparent",
    },
    buttonUtility: {
      backgroundColor: theme.colors.buttonUtility,
    },
    buttonOperator: {
      backgroundColor: theme.colors.buttonOperator,
    },
    buttonPressed: {
      opacity: 0.65,
    },
    buttonText: {
      color: theme.colors.buttonText,
      fontSize: 34,
      fontWeight: "400",
    },
    operatorText: {
      color: theme.colors.operatorText,
    },
    sciNumButtonText: {
      fontSize: 26,
    },
    utilityText: {
      color: theme.colors.utilityText,
    },
    fractionKeypad: {
      flex: 1,
      gap: 6,
      paddingBottom: 12,
      paddingHorizontal: 10,
      paddingTop: 8,
    },
    fractionTopRow: {
      flexDirection: "row",
      gap: 6,
    },
    fractionBody: {
      flex: 1,
      flexDirection: "row",
      gap: 6,
    },
    fractionNumberBlock: {
      flex: 1,
      gap: 4,
    },
    fractionStackedPads: {
      flex: 1.4,
      gap: 4,
    },
    fractionOperatorColumn: {
      flex: 0.55,
      gap: 6,
    },
    fractionSmallRow: {
      flex: 1,
      flexDirection: "row",
      gap: 4,
    },
    fractionButton: {
      alignItems: "center",
      backgroundColor: theme.colors.buttonNumber,
      borderRadius: 8,
      flex: 1,
      justifyContent: "center",
      paddingHorizontal: 2,
      paddingVertical: 8,
    },
    fractionWideButton: {
      flex: 2.07,
    },
    fractionButtonText: {
      color: theme.colors.buttonText,
      fontSize: 30,
      fontWeight: "300",
    },
    fractionInputBar: {
      backgroundColor: theme.colors.displayText,
      height: 2,
      marginHorizontal: 4,
      opacity: 0.7,
    },
    percentageTopBar: {
      alignItems: "center",
      flexDirection: "row",
      gap: 8,
      justifyContent: "space-between",
      paddingHorizontal: 12,
      paddingTop: 4,
    },
    percentageTitleButton: {
      alignItems: "center",
      flex: 1,
      flexDirection: "row",
      gap: 8,
      minHeight: 44,
    },
    percentageTitle: {
      color: theme.colors.topText,
      flexShrink: 1,
      fontSize: 22,
      fontWeight: "600",
    },
    percentageChevron: {
      color: theme.colors.topText,
      fontSize: 30,
      fontWeight: "600",
      marginTop: -4,
    },
    percentageForm: {
      gap: 8,
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    percentageInputRow: {
      alignItems: "center",
      backgroundColor: "rgba(255, 255, 255, 0.08)",
      borderRadius: 8,
      flexDirection: "row",
      justifyContent: "space-between",
      minHeight: 54,
      paddingHorizontal: 18,
    },
    percentageInputRowActive: {
      backgroundColor: "rgba(255, 255, 255, 0.12)",
    },
    percentageInputLabel: {
      color: theme.colors.displayText,
      flex: 1,
      fontSize: 24,
      fontWeight: "400",
    },
    percentageInputValue: {
      color: theme.colors.mutedText,
      flex: 1,
      fontSize: 30,
      fontWeight: "500",
      textAlign: "right",
    },
    percentageAnswerRow: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      minHeight: 52,
      paddingHorizontal: 18,
    },
    percentageAnswerLabel: {
      color: theme.colors.displayText,
      fontSize: 30,
      fontWeight: "700",
    },
    percentageAnswerValue: {
      color: theme.colors.mutedText,
      flex: 1,
      fontSize: 30,
      fontWeight: "700",
      textAlign: "right",
    },
    percentageKeypad: {
      flex: 1,
      gap: 8,
      justifyContent: "flex-end",
      paddingBottom: 14,
      paddingHorizontal: 8,
      paddingTop: 10,
    },
    percentageKeypadRow: {
      flexDirection: "row",
      gap: 8,
      minHeight: 72,
    },
    calculusModeSwitch: {
      alignSelf: "center",
      backgroundColor: "rgba(255, 255, 255, 0.08)",
      borderRadius: 8,
      flexDirection: "row",
      gap: 4,
      marginTop: 8,
      padding: 4,
      width: 220,
    },
    calculusModeButton: {
      alignItems: "center",
      borderRadius: 6,
      flex: 1,
      justifyContent: "center",
      minHeight: 38,
    },
    calculusModeButtonActive: {
      backgroundColor: theme.colors.buttonOperator,
    },
    calculusModeText: {
      color: theme.colors.mutedText,
      fontSize: 22,
      fontWeight: "600",
    },
    calculusModeTextActive: {
      color: theme.colors.operatorText,
    },
    calculusForm: {
      gap: 8,
      paddingHorizontal: 16,
      paddingTop: 16,
    },
    calculusInputRow: {
      alignItems: "center",
      backgroundColor: "rgba(255, 255, 255, 0.08)",
      borderRadius: 8,
      flexDirection: "row",
      justifyContent: "space-between",
      minHeight: 56,
      paddingHorizontal: 18,
    },
    calculusInputRowActive: {
      backgroundColor: "rgba(255, 255, 255, 0.12)",
    },
    calculusBoundsRow: {
      flexDirection: "row",
      gap: 8,
    },
    calculusBoundInput: {
      flex: 1,
      minHeight: 56,
      paddingHorizontal: 14,
    },
    calculusInputLabel: {
      color: theme.colors.displayText,
      flex: 1,
      fontSize: 24,
      fontWeight: "400",
    },
    calculusInputValue: {
      color: theme.colors.mutedText,
      flex: 1.35,
      fontSize: 30,
      fontWeight: "500",
      textAlign: "right",
    },
    calculusAnswerRow: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      minHeight: 52,
      paddingHorizontal: 18,
    },
    calculusAnswerLabel: {
      color: theme.colors.displayText,
      fontSize: 24,
      fontWeight: "700",
    },
    calculusAnswerValue: {
      color: theme.colors.mutedText,
      flex: 1,
      fontSize: 28,
      fontWeight: "700",
      textAlign: "left",
    },
    calculusKeypad: {
      flex: 1,
      gap: 5,
      justifyContent: "flex-end",
      paddingBottom: 10,
      paddingHorizontal: 8,
      paddingTop: 6,
    },
    calculusKeypadRow: {
      flexDirection: "row",
      gap: 5,
      minHeight: 44,
    },
    calculusButton: {
      alignItems: "center",
      backgroundColor: theme.colors.buttonNumber,
      borderRadius: 8,
      flex: 1,
      justifyContent: "center",
      minHeight: 44,
      paddingHorizontal: 4,
    },
    calculusButtonText: {
      color: theme.colors.buttonText,
      fontSize: 22,
      fontWeight: "400",
    },
    percentagePickerBackdrop: {
      backgroundColor: "rgba(0, 0, 0, 0.96)",
      flex: 1,
      justifyContent: "flex-end",
    },
    percentagePickerSheet: {
      backgroundColor: "#000",
      flex: 1,
      paddingTop: 18,
    },
    percentagePickerHandle: {
      alignSelf: "center",
      backgroundColor: "rgba(80, 75, 130, 0.45)",
      borderRadius: 6,
      height: 6,
      marginBottom: 38,
      width: 64,
    },
    percentagePickerHeader: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      paddingHorizontal: 24,
      paddingBottom: 44,
    },
    percentagePickerTitle: {
      color: "#fff",
      fontSize: 34,
      fontWeight: "700",
    },
    percentagePickerClose: {
      alignItems: "center",
      backgroundColor: "#2b2b2d",
      borderRadius: 28,
      height: 56,
      justifyContent: "center",
      width: 56,
    },
    percentagePickerCloseText: {
      color: "#fff",
      fontSize: 42,
      fontWeight: "300",
      lineHeight: 48,
    },
    percentagePickerList: {
      paddingBottom: 36,
    },
    percentagePickerItem: {
      alignItems: "center",
      borderBottomColor: "rgba(255, 255, 255, 0.14)",
      borderBottomWidth: StyleSheet.hairlineWidth,
      flexDirection: "row",
      justifyContent: "space-between",
      minHeight: 126,
      paddingHorizontal: 34,
      paddingVertical: 22,
    },
    percentagePickerItemActive: {
      backgroundColor: "#2d2d2f",
      borderRadius: 14,
      marginHorizontal: 12,
    },
    percentagePickerItemText: {
      flex: 1,
      gap: 12,
      paddingRight: 16,
    },
    percentagePickerItemTitle: {
      color: "#f7f7f7",
      fontSize: 27,
      fontWeight: "400",
    },
    percentagePickerItemExample: {
      color: "rgba(255, 255, 255, 0.62)",
      fontSize: 22,
      fontWeight: "400",
    },
    percentagePickerCheck: {
      alignItems: "center",
      backgroundColor: "#f5f5f5",
      borderRadius: 24,
      height: 48,
      justifyContent: "center",
      width: 48,
    },
    percentagePickerCheckText: {
      color: "#111",
      fontSize: 34,
      fontWeight: "600",
      lineHeight: 38,
    },
  } as const;
}
